package com.dbms.csmq.model.impact;

import com.dbms.csmq.model.impact.common.ImpactModule;

import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;

import org.apache.log4j.Logger;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 30 10:25:12 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImpactModuleImpl extends ApplicationModuleImpl implements ImpactModule {
    /**
     * This is the default constructor (do not remove).
     */
    public ImpactModuleImpl() {
    }

    public static final Logger logger = Logger.getLogger(ImpactModuleImpl.class);

    /**
     * Container's getter for MedDRAImpactVO1.
     * @return MedDRAImpactVO1
     */
    public ViewObjectImpl getMedDRAImpactVO1() {
        return (ViewObjectImpl) findViewObject("MedDRAImpactVO1");
    }

    /**
     * Container's getter for NewPTsVO1.
     * @return NewPTsVO1
     */
    public ViewObjectImpl getNewPTsVO1() {
        return (ViewObjectImpl) findViewObject("NewPTsVO1");
    }

    /**
     * Container's getter for DraftImpactVO1.
     * @return DraftImpactVO1
     */
    public ViewObjectImpl getDraftImpactVO1() {
        return (ViewObjectImpl) findViewObject("DraftImpactVO1");
    }

    /**
     * Container's getter for HistoricalImpactVO1.
     * @return HistoricalImpactVO1
     */
    public ViewObjectImpl getHistoricalImpactVO1() {
        return (ViewObjectImpl) findViewObject("HistoricalImpactVO1");
    }

    /**
     * Container's getter for CurrentImpactVO1.
     * @return CurrentImpactVO1
     */
    public ViewObjectImpl getCurrentImpactVO1() {
        return (ViewObjectImpl) findViewObject("CurrentImpactVO1");
    }

    /**
     * Container's getter for SOCsWithNewPTsVO1.
     * @return SOCsWithNewPTsVO1
     */
    public SOCsWithNewPTsVOImpl getSOCsWithNewPTsVO1() {
        return (SOCsWithNewPTsVOImpl) findViewObject("SOCsWithNewPTsVO1");
    }

    /**
     * Container's getter for LastMVUpdateViewObj1.
     * @return LastMVUpdateViewObj1
     */
    public ViewObjectImpl getLastMVUpdateViewObj1() {
        return (ViewObjectImpl) findViewObject("LastMVUpdateViewObj1");
    }

    /**
     * Container's getter for ImpactSearchListVO1.
     * @return ImpactSearchListVO1
     */
    public ImpactSearchListVOImpl getImpactSearchListVO1() {
        return (ImpactSearchListVOImpl) findViewObject("ImpactSearchListVO1");
    }

    /**
     * Container's getter for ImpactSearchListVO_NMQ_Y.
     * @return ImpactSearchListVO_NMQ_Y
     */
    public ImpactSearchListVOImpl getImpactSearchListVO_NMQ_Y() {
        return (ImpactSearchListVOImpl) findViewObject("ImpactSearchListVO_NMQ_Y");
    }

    /**
     * Container's getter for ImpactSearchListVO_MQ_Y.
     * @return ImpactSearchListVO_MQ_Y
     */
    public ImpactSearchListVOImpl getImpactSearchListVO_MQ_Y() {
        return (ImpactSearchListVOImpl) findViewObject("ImpactSearchListVO_MQ_Y");
    }

    /**
     * Container's getter for ImpactSearchListVO_MQ_N.
     * @return ImpactSearchListVO_MQ_N
     */
    public ImpactSearchListVOImpl getImpactSearchListVO_MQ_N() {
        return (ImpactSearchListVOImpl) findViewObject("ImpactSearchListVO_MQ_N");
    }

    /**
     * Container's getter for ImpactSearchListVO_NMQ_N.
     * @return ImpactSearchListVO_NMQ_N
     */
    public ImpactSearchListVOImpl getImpactSearchListVO_NMQ_N() {
        return (ImpactSearchListVOImpl) findViewObject("ImpactSearchListVO_NMQ_N");
    }

    /**
     * Container's getter for ImpactSearchListVO_CMQ_Y.
     * @return ImpactSearchListVO_CMQ_Y
     */
    public ImpactSearchListVOImpl getImpactSearchListVO_CMQ_Y() {
        return (ImpactSearchListVOImpl) findViewObject("ImpactSearchListVO_CMQ_Y");
    }

    /**
     * Container's getter for ImpactSearchListVO_CMQ_N.
     * @return ImpactSearchListVO_CMQ_N
     */
    public ImpactSearchListVOImpl getImpactSearchListVO_CMQ_N() {
        return (ImpactSearchListVOImpl) findViewObject("ImpactSearchListVO_CMQ_N");
    }

    /**
     * Container's getter for PreviousVerImpactSearchListVO_CMQ_N.
     * @return PreviousVerImpactSearchListVO_CMQ_N
     */
    public ViewObjectImpl getPreviousVerImpactSearchListVO_CMQ_N() {
        return (ViewObjectImpl) findViewObject("PreviousVerImpactSearchListVO_CMQ_N");
    }

    /**
     * Container's getter for PreviousVerImpactSearchListVO_CMQ_Y.
     * @return PreviousVerImpactSearchListVO_CMQ_Y
     */
    public ViewObjectImpl getPreviousVerImpactSearchListVO_CMQ_Y() {
        return (ViewObjectImpl) findViewObject("PreviousVerImpactSearchListVO_CMQ_Y");
    }

    /**
     * Container's getter for PreviousVerImpactSearchListVO_MQ_N.
     * @return PreviousVerImpactSearchListVO_MQ_N
     */
    public ViewObjectImpl getPreviousVerImpactSearchListVO_MQ_N() {
        return (ViewObjectImpl) findViewObject("PreviousVerImpactSearchListVO_MQ_N");
    }

    /**
     * Container's getter for PreviousVerImpactSearchListVO_MQ_Y.
     * @return PreviousVerImpactSearchListVO_MQ_Y
     */
    public ViewObjectImpl getPreviousVerImpactSearchListVO_MQ_Y() {
        return (ViewObjectImpl) findViewObject("PreviousVerImpactSearchListVO_MQ_Y");
    }

    /**
     * Container's getter for PreviousVerImpactSearchListVO_NMQ_N.
     * @return PreviousVerImpactSearchListVO_NMQ_N
     */
    public ViewObjectImpl getPreviousVerImpactSearchListVO_NMQ_N() {
        return (ViewObjectImpl) findViewObject("PreviousVerImpactSearchListVO_NMQ_N");
    }

    /**
     * Container's getter for PreviousVerImpactSearchListVO_NMQ_Y.
     * @return PreviousVerImpactSearchListVO_NMQ_Y
     */
    public ViewObjectImpl getPreviousVerImpactSearchListVO_NMQ_Y() {
        return (ViewObjectImpl) findViewObject("PreviousVerImpactSearchListVO_NMQ_Y");
    }

    /**
     * Container's getter for PreviousVerImpactSearchListVO1.
     * @return PreviousVerImpactSearchListVO1
     */
    public ViewObjectImpl getPreviousVerImpactSearchListVO1() {
        return (ViewObjectImpl) findViewObject("PreviousVerImpactSearchListVO1");
    }

    public void onPreviousVerImpactSearch(String searchLevelStr, String searchTermStr, String searchCodeStr) {
        System.out.println(" Starts executing onPreviousVerImpactSearch() searchLevelStr=" + searchLevelStr +
                           ";; searchTermStr=" + searchTermStr + ":; searchCodeStr=" + searchCodeStr);
        exceutePrevImpactSearchVC(getPreviousVerImpactSearchListVO_CMQ_N(), searchLevelStr, searchTermStr,
                                  searchCodeStr);
        exceutePrevImpactSearchVC(getPreviousVerImpactSearchListVO_CMQ_Y(), searchLevelStr, searchTermStr,
                                  searchCodeStr);
        exceutePrevImpactSearchVC(getPreviousVerImpactSearchListVO_MQ_N(), searchLevelStr, searchTermStr,
                                  searchCodeStr);
        exceutePrevImpactSearchVC(getPreviousVerImpactSearchListVO_MQ_Y(), searchLevelStr, searchTermStr,
                                  searchCodeStr);
        exceutePrevImpactSearchVC(getPreviousVerImpactSearchListVO_NMQ_N(), searchLevelStr, searchTermStr,
                                  searchCodeStr);
        exceutePrevImpactSearchVC(getPreviousVerImpactSearchListVO_NMQ_Y(), searchLevelStr, searchTermStr,
                                  searchCodeStr);
        System.out.println(" End of execution onPreviousVerImpactSearch() -------------------");
    }

    private void exceutePrevImpactSearchVC(ViewObjectImpl previousVerImpactSearchListVO, String searchLevelStr,
                                           String searchTermStr, String searchCodeStr) {
        previousVerImpactSearchListVO.setNamedWhereClauseParam("bindLevelNumber", searchLevelStr);
        previousVerImpactSearchListVO.setNamedWhereClauseParam("bindTerm", searchTermStr);
        previousVerImpactSearchListVO.setNamedWhereClauseParam("bindCode", searchCodeStr);
        ViewCriteria vc = previousVerImpactSearchListVO.getViewCriteria("PreviousVerImpactSearchListVOCriteria");
        previousVerImpactSearchListVO.applyViewCriteria(vc);
        previousVerImpactSearchListVO.executeQuery();
        System.out.println("exceutePrevImpactSearchVC() QUERY --> " + previousVerImpactSearchListVO.getQuery());
    }
}

