package com.dbms.csmq.model.impact;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 07 16:04:42 EST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImpactSearchListVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ImpactSearchListVOImpl() {
    }

    /**
     * Returns the bind variable value for showImpact.
     * @return bind variable value for showImpact
     */
    public String getshowImpact() {
        return (String)getNamedWhereClauseParam("showImpact");
    }

    /**
     * Sets <code>value</code> for bind variable showImpact.
     * @param value value to bind as showImpact
     */
    public void setshowImpact(String value) {
        setNamedWhereClauseParam("showImpact", value);
    }

    /**
     * Returns the bind variable value for mqType.
     * @return bind variable value for mqType
     */
    public String getmqType() {
        return (String)getNamedWhereClauseParam("mqType");
    }

    /**
     * Sets <code>value</code> for bind variable mqType.
     * @param value value to bind as mqType
     */
    public void setmqType(String value) {
        setNamedWhereClauseParam("mqType", value);
    }


    /**
     * Returns the variable value for bindTerm.
     * @return variable value for bindTerm
     */
    public String getbindTerm() {
        return (String) ensureVariableManager().getVariableValue("bindTerm");
    }

    /**
     * Sets <code>value</code> for variable bindTerm.
     * @param value value to bind as bindTerm
     */
    public void setbindTerm(String value) {
        ensureVariableManager().setVariableValue("bindTerm", value);
    }

    /**
     * Returns the variable value for bindStatus.
     * @return variable value for bindStatus
     */
    public String getbindStatus() {
        return (String) ensureVariableManager().getVariableValue("bindStatus");
    }

    /**
     * Sets <code>value</code> for variable bindStatus.
     * @param value value to bind as bindStatus
     */
    public void setbindStatus(String value) {
        ensureVariableManager().setVariableValue("bindStatus", value);
    }

    /**
     * Returns the variable value for bindCode.
     * @return variable value for bindCode
     */
    public String getbindCode() {
        return (String) ensureVariableManager().getVariableValue("bindCode");
    }

    /**
     * Sets <code>value</code> for variable bindCode.
     * @param value value to bind as bindCode
     */
    public void setbindCode(String value) {
        ensureVariableManager().setVariableValue("bindCode", value);
    }

    /**
     * Returns the variable value for bindState.
     * @return variable value for bindState
     */
    public String getbindState() {
        return (String) ensureVariableManager().getVariableValue("bindState");
    }

    /**
     * Sets <code>value</code> for variable bindState.
     * @param value value to bind as bindState
     */
    public void setbindState(String value) {
        ensureVariableManager().setVariableValue("bindState", value);
    }
}
