package com.dbms.csmq.model.impact;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 25 02:36:36 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NewPTReportVVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NewPTReportVVOImpl() {
    }

    /**
     * Returns the bind variable value for bindTermCode.
     * @return bind variable value for bindTermCode
     */
    public String getbindTermCode() {
        return (String) getNamedWhereClauseParam("bindTermCode");
    }

    /**
     * Sets <code>value</code> for bind variable bindTermCode.
     * @param value value to bind as bindTermCode
     */
    public void setbindTermCode(String value) {
        setNamedWhereClauseParam("bindTermCode", value);
    }

    /**
     * Returns the bind variable value for bindTerm.
     * @return bind variable value for bindTerm
     */
    public String getbindTerm() {
        return (String) getNamedWhereClauseParam("bindTerm");
    }

    /**
     * Sets <code>value</code> for bind variable bindTerm.
     * @param value value to bind as bindTerm
     */
    public void setbindTerm(String value) {
        setNamedWhereClauseParam("bindTerm", value);
    }

    /**
     * Returns the bind variable value for bindProduct.
     * @return bind variable value for bindProduct
     */
    public String getbindProduct() {
        return (String) getNamedWhereClauseParam("bindProduct");
    }

    /**
     * Sets <code>value</code> for bind variable bindProduct.
     * @param value value to bind as bindProduct
     */
    public void setbindProduct(String value) {
        setNamedWhereClauseParam("bindProduct", value);
    }
}

