package com.dbms.csmq.model.NMQ.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 31 18:53:52 IST 2016
// ---------------------------------------------------------------------
public interface NMQModule extends ApplicationModule {
    Boolean isUpgradePending();
}
