package com.dbms.csmq.model.designee;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 02 01:00:10 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MqDesigneeListImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MqDesigneeListImpl() {
    }
    
    /**
     * Returns the bind variable value for state.
     * @return bind variable value for state
     */
    public String getbindContentID() {
        return (String) getNamedWhereClauseParam("bindContentID");
    }

    /**
     * Sets <code>value</code> for bind variable state.
     * @param value value to bind as state
     */
    public void setbindContentID(String value) {
        setNamedWhereClauseParam("bindContentID", value);
    }
}

