package com.dbms.csmq.model.publish;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 15 19:14:32 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PublishedIAMQVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PublishedIAMQVOImpl() {
    }

    /**
     * Returns the bind variable value for bindDefaultGroup.
     * @return bind variable value for bindDefaultGroup
     */
    public String getbindDefaultGroup() {
        return (String) getNamedWhereClauseParam("bindDefaultGroup");
    }

    /**
     * Sets <code>value</code> for bind variable bindDefaultGroup.
     * @param value value to bind as bindDefaultGroup
     */
    public void setbindDefaultGroup(String value) {
        setNamedWhereClauseParam("bindDefaultGroup", value);
    }

    /**
     * Returns the bind variable value for state.
     * @return bind variable value for state
     */
    public String getstate() {
        return (String) getNamedWhereClauseParam("state");
    }

    /**
     * Sets <code>value</code> for bind variable state.
     * @param value value to bind as state
     */
    public void setstate(String value) {
        setNamedWhereClauseParam("state", value);
    }
}

