package com.dbms.csmq.model.publish;


import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 15 19:20:05 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PublishModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PublishModuleImpl() {
    }

    /**
     * Container's getter for ViewObjTermsByState1.
     * @return ViewObjTermsByState1
     */
    public ViewObjTermsByStateImpl getViewObjTermsByState1() {
        return (ViewObjTermsByStateImpl) findViewObject("ViewObjTermsByState1");
    }

    /**
     * Container's getter for ViewObjActivationErrors_Contents1.
     * @return ViewObjActivationErrors_Contents1
     */
    public ViewObjectImpl getViewObjActivationErrors_Contents1() {
        return (ViewObjectImpl) findViewObject("ViewObjActivationErrors_Contents1");
    }

    /**
     * Container's getter for ViewObjActivationErrors_Relations1.
     * @return ViewObjActivationErrors_Relations1
     */
    public ViewObjectImpl getViewObjActivationErrors_Relations1() {
        return (ViewObjectImpl) findViewObject("ViewObjActivationErrors_Relations1");
    }

    /**
     * Container's getter for PublishedIAMQVO1.
     * @return PublishedIAMQVO1
     */
    public PublishedIAMQVOImpl getPublishedIAMQVO1() {
        return (PublishedIAMQVOImpl) findViewObject("PublishedIAMQVO1");
    }

    /**
     * Container's getter for PublishedMQVO1.
     * @return PublishedMQVO1
     */
    public PublishedMQVOImpl getPublishedMQVO1() {
        return (PublishedMQVOImpl) findViewObject("PublishedMQVO1");
    }
}

