package com.dbms.csmq.model.report;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 29 17:35:24 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GenerateCurrentMedraQueryRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Mqcd {
            protected Object get(GenerateCurrentMedraQueryRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GenerateCurrentMedraQueryRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Extension {
            protected Object get(GenerateCurrentMedraQueryRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GenerateCurrentMedraQueryRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Mqname {
            protected Object get(GenerateCurrentMedraQueryRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GenerateCurrentMedraQueryRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Mqprodct {
            protected Object get(GenerateCurrentMedraQueryRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GenerateCurrentMedraQueryRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Mqlevel {
            protected Object get(GenerateCurrentMedraQueryRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GenerateCurrentMedraQueryRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Mqscp {
            protected Object get(GenerateCurrentMedraQueryRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GenerateCurrentMedraQueryRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Dictver {
            protected Object get(GenerateCurrentMedraQueryRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GenerateCurrentMedraQueryRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Status {
            protected Object get(GenerateCurrentMedraQueryRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GenerateCurrentMedraQueryRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Mqalgo {
            protected Object get(GenerateCurrentMedraQueryRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GenerateCurrentMedraQueryRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Mqcrtev {
            protected Object get(GenerateCurrentMedraQueryRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GenerateCurrentMedraQueryRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Mqgroup {
            protected Object get(GenerateCurrentMedraQueryRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GenerateCurrentMedraQueryRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Totalrows {
            protected Object get(GenerateCurrentMedraQueryRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GenerateCurrentMedraQueryRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(GenerateCurrentMedraQueryRowImpl object);

        protected abstract void put(GenerateCurrentMedraQueryRowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int MQCD = AttributesEnum.Mqcd.index();
    public static final int EXTENSION = AttributesEnum.Extension.index();
    public static final int MQNAME = AttributesEnum.Mqname.index();
    public static final int MQPRODCT = AttributesEnum.Mqprodct.index();
    public static final int MQLEVEL = AttributesEnum.Mqlevel.index();
    public static final int MQSCP = AttributesEnum.Mqscp.index();
    public static final int DICTVER = AttributesEnum.Dictver.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int MQALGO = AttributesEnum.Mqalgo.index();
    public static final int MQCRTEV = AttributesEnum.Mqcrtev.index();
    public static final int MQGROUP = AttributesEnum.Mqgroup.index();
    public static final int TOTALROWS = AttributesEnum.Totalrows.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GenerateCurrentMedraQueryRowImpl() {
    }
}

