package com.dbms.csmq.model.report;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 29 17:35:26 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GenerateCurrentMedraQueryImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GenerateCurrentMedraQueryImpl() {
    }
}

