package com.dbms.csmq.model.impact.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 30 10:59:15 IST 2016
// ---------------------------------------------------------------------
public interface ImpactModule extends ApplicationModule {
    void onPreviousVerImpactSearch(String searchLevelStr, String searchTermStr, String searchCodeStr);

    void loadPrevVersionCurrentMQDetails(Long dictContentId, Boolean showImpactedOnly);

    void loadPrevVersionCurrentNFurteMQDetails(Long dictContentId, Boolean showImpactedOnly);

    void loadPrevVersionFurteMQDetails(Long dictContentId, Boolean showImpactedOnly);

    void onPreviousVerImpactSearch(String searchLevelStr, String searchTermStr, String searchCodeStr, String status,
                                   String state, String searchProduct);

    void onCurrentVerImpactSearch(String searchLevelStr, String searchTermStr, String searchCodeStr, String status,
                                  String state, String searchProduct);
}

