package com.dbms.csmq.model.impact.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 30 10:59:15 IST 2016
// ---------------------------------------------------------------------
public interface ImpactModule extends ApplicationModule {
    void onPreviousVerImpactSearch(String searchLevelStr, String searchTermStr, String searchCodeStr);

    void loadPrevVersionCurrentMQDetails(Long dictContentId, Boolean showImpactedOnly);

    void loadPrevVersionCurrentNFurteMQDetails(Long dictContentId, Boolean showImpactedOnly);

    void loadPrevVersionFurteMQDetails(Long dictContentId, Boolean showImpactedOnly);

    void onPreviousVerImpactSearch(String searchLevelStr, String searchTermStr, String searchCodeStr, String status,
                                   String state, String searchProduct);

    void onCurrentVerImpactSearch(String searchLevelStr, String searchTermStr, String searchCodeStr, String status,
                                  String state, String searchProduct);

    void ImpactAssesmentClearSelectMQ();

    void executeImpactSearchListVO_CMQ_N();

    void executeImpactSearchListVO_CMQ_Y();

    void executeImpactSearchListVO_MQ_N();

    void executeImpactSearchListVO_MQ_Y();

    void executeImpactSearchListVO_NMQ_N();

    void executeImpactSearchListVO_NMQ_Y();

    void executePreviousImpactSearchListVO_CMQ_N();

    void executePreviousImpactSearchListVO_CMQ_Y();

    void executePreviousImpactSearchListVO_MQ_N();

    void executePreviousImpactSearchListVO_MQ_Y();

    void executePreviousImpactSearchListVO_NMQ_N();

    void executePreviousImpactSearchListVO_NMQ_Y();

    void previousImpactVersionClearSelectMQ();

    void onCurrentVerImpactCMQSearch(String searchLevelStr, String searchTermStr, String searchCodeStr, String status,
                                     String state, String searchProduct);

    void onCurrentVerImpactNMQSearch(String searchLevelStr, String searchTermStr, String searchCodeStr, String status,
                                     String state, String searchProduct);

    void onCurrentVerImpactNonCMQSearch(String searchLevelStr, String searchTermStr, String searchCodeStr,
                                        String status, String state, String searchProduct);

    void onCurrentVerImpactNonNMQSearch(String searchLevelStr, String searchTermStr, String searchCodeStr,
                                        String status, String state, String searchProduct);

    void onCurrentVerImpactNonSMQSearch(String searchLevelStr, String searchTermStr, String searchCodeStr,
                                        String status, String state, String searchProduct);

    void onCurrentVerImpactSMQSearch(String searchLevelStr, String searchTermStr, String searchCodeStr, String status,
                                     String state, String searchProduct);

    void onPreviousVerImpactCMQSearch(String searchLevelStr, String searchTermStr, String searchCodeStr, String status,
                                      String state, String searchProduct);

    void onPreviousVerImpactNMQSearch(String searchLevelStr, String searchTermStr, String searchCodeStr, String status,
                                      String state, String searchProduct);

    void onPreviousVerImpactNonCMQSearch(String searchLevelStr, String searchTermStr, String searchCodeStr,
                                         String status, String state, String searchProduct);

    void onPreviousVerImpactNonNMQSearch(String searchLevelStr, String searchTermStr, String searchCodeStr,
                                         String status, String state, String searchProduct);

    void onPreviousVerImpactNonSMQSearch(String searchLevelStr, String searchTermStr, String searchCodeStr,
                                         String status, String state, String searchProduct);

    void onPreviousVerImpactSMQSearch(String searchLevelStr, String searchTermStr, String searchCodeStr, String status,
                                      String state, String searchProduct);
}

