package com.dbms.csmq.model.dictionary;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 27 23:22:10 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CurrentDictionaryPTVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ShortName {
            protected Object get(CurrentDictionaryPTVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CurrentDictionaryPTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Name {
            protected Object get(CurrentDictionaryPTVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CurrentDictionaryPTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Description {
            protected Object get(CurrentDictionaryPTVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CurrentDictionaryPTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Version {
            protected Object get(CurrentDictionaryPTVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CurrentDictionaryPTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(CurrentDictionaryPTVORowImpl object);

        protected abstract void put(CurrentDictionaryPTVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int SHORTNAME = AttributesEnum.ShortName.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int VERSION = AttributesEnum.Version.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CurrentDictionaryPTVORowImpl() {
    }
}

