package com.dbms.csmq.model.dictionary;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 27 23:40:06 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LevelsByDictionaryPTVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Name {
            protected Object get(LevelsByDictionaryPTVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(LevelsByDictionaryPTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ShortName {
            protected Object get(LevelsByDictionaryPTVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(LevelsByDictionaryPTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Querytypelevel {
            protected Object get(LevelsByDictionaryPTVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(LevelsByDictionaryPTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DefLevelId {
            protected Object get(LevelsByDictionaryPTVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(LevelsByDictionaryPTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(LevelsByDictionaryPTVORowImpl object);

        protected abstract void put(LevelsByDictionaryPTVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int NAME = AttributesEnum.Name.index();
    public static final int SHORTNAME = AttributesEnum.ShortName.index();
    public static final int QUERYTYPELEVEL = AttributesEnum.Querytypelevel.index();
    public static final int DEFLEVELID = AttributesEnum.DefLevelId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LevelsByDictionaryPTVORowImpl() {
    }
}

