package com.dbms.csmq.model.dictionary;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 27 23:40:08 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LevelsByDictionaryPTVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LevelsByDictionaryPTVOImpl() {
    }
}

