package com.dbms.csmq.model.dictionary;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 06 22:46:43 EDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LevelsByDictionaryVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LevelsByDictionaryVOImpl() {
    }

    /**
     * Returns the bind variable value for dictShortName.
     * @return bind variable value for dictShortName
     */
    public String getdictShortName() {
        return (String)getNamedWhereClauseParam("dictShortName");
    }

    /**
     * Sets <code>value</code> for bind variable dictShortName.
     * @param value value to bind as dictShortName
     */
    public void setdictShortName(String value) {
        setNamedWhereClauseParam("dictShortName", value);
    }

    /**
     * Returns the variable value for bindShortName.
     * @return variable value for bindShortName
     */
    public String getbindShortName() {
        return (String) ensureVariableManager().getVariableValue("bindShortName");
    }

    /**
     * Sets <code>value</code> for variable bindShortName.
     * @param value value to bind as bindShortName
     */
    public void setbindShortName(String value) {
        ensureVariableManager().setVariableValue("bindShortName", value);
    }
}
