package com.dbms.csmq.model.am.common;

import java.util.HashMap;
import java.util.Hashtable;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 22 17:12:19 IST 2015
// ---------------------------------------------------------------------
public interface CQTAppModule extends ApplicationModule {
    String activate(String dictContentID, String mQCode, String draftRelGroup, String status, String userRole,
                    String userName);

    String activateGroup(String groupName);


    boolean delete(String dictContentID, String predictGroupName);


    java.sql.Date getLastActivationDate(String dictContentID, java.sql.Date transEndDate);

    void initBindingContext();

    String refreshImpactMVs();


    String saveIAInfNotes(String noteName, String content, String currentDictContentID, String currentTermLevel,
                          String userName, String userRole);

    String saveInfNotes(String noteName, String content, String currentFilterDictionaryShortName,
                        String currentPredictGroups, String currentDictContentID, String currentTermLevel,
                        String userName, String userRole, String extension);

    void setCurrentFilterDictionary(String shortName);


    boolean updateMQDesignee(String dictContentID, String designee);

    String retire(String dictContentID, String mQCode, String defDraftRelGroup, String userRole, String userName);


    String copyAllRelations(String copiedDictContentID, String currentDictContentID, String currentPredictGroups,
                            String userName);


    String activateGroupInCheckMode(String groupName);

    HashMap changeState(String dictContentIDs, String state, String currentUser, String currentUserRole, Date dueDate,
                        String comment, String activationGroup);


    HashMap saveDetails(String currentFilterDictionaryShortName, String currentPredictGroups, String tempName,
                        String currentProduct, String currentTermLevel, String currentScope, String currentMQALGO,
                        String currentMQCRTEV, String currentMQGROUP, String currentContentCode, String updateParam,
                        String currentRequestor, String currentDictContentID, String userRole,
                        String currentPendingStatus, String currentDesignee);


    HashMap<String, String> changeStateFromDraftToPublish(String dictContentIDs, String state, String currentUser,
                                                          String currentUserRole, Date dueDate, String comment,
                                                          String activationGroup);

    Hashtable<String, String> getActivationInfo(String dictContentID, String dictionaryID);

    HashMap<String, String> saveIADetails(String tempName, String currentProduct, String currentTermLevel,
                                          String currentScope, String currentMQALGO, String currentMQCRTEV,
                                          String currentMQGROUP, String currentContentCode, String updateParam,
                                          String currentRequestor, String currentDictContentID, String userRole,
                                          String currentDesignee);

    HashMap<String, String> setDefaultIAState(String dictContentIDs, String currentUser, String currentUserRole);
}

