package com.dbms.csmq.model.NMQ.client;

import com.dbms.csmq.model.NMQ.common.NMQModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 31 18:53:52 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NMQModuleClient extends ApplicationModuleImpl implements NMQModule {
    /**
     * This is the default constructor (do not remove).
     */
    public NMQModuleClient() {
    }

    public Boolean isUpgradePending() {
        Object _ret = this.riInvokeExportedMethod(this,"isUpgradePending",null,null);
        return (Boolean)_ret;
    }
}
