package com.dbms.csmq.model.search.common;

import java.math.BigDecimal;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 15 15:18:22 IST 2016
// ---------------------------------------------------------------------
public interface SearchModule extends ApplicationModule {
    void loadHistoricTermInformation(BigDecimal dictContentId, String effectiveDTStr);

    void loadHistoricTermHierarchyInformation(BigDecimal dictContentId, String effectiveDTStr);

    void loadMQDetailedDetailedTermHierarchyInformation(BigDecimal dictContentId, String tMSRecordStatus,
                                                        String activationGroup);

    void executeMQDesignee(String contentIDs);

    String addDesignee(String contentId, String desgineeName);

    String removeDesignee(String contentId, String desgineeName);
}
