package com.dbms.csmq.model.search;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 18 23:49:46 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExportSearchPTRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        MeddraCode {
            protected Object get(ExportSearchPTRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ExportSearchPTRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MeddraTerm {
            protected Object get(ExportSearchPTRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ExportSearchPTRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PtCode {
            protected Object get(ExportSearchPTRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ExportSearchPTRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PtName {
            protected Object get(ExportSearchPTRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ExportSearchPTRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(ExportSearchPTRowImpl object);

        protected abstract void put(ExportSearchPTRowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int MEDDRACODE = AttributesEnum.MeddraCode.index();
    public static final int MEDDRATERM = AttributesEnum.MeddraTerm.index();
    public static final int PTCODE = AttributesEnum.PtCode.index();
    public static final int PTNAME = AttributesEnum.PtName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ExportSearchPTRowImpl() {
    }
}

