package com.dbms.csmq.model.search;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 18 23:49:49 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExportSearchPTImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ExportSearchPTImpl() {
    }
}

