package com.dbms.csmq.model.search;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 21 15:52:39 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SimplePTSearchRVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SimplePTSearchRVOImpl() {
    }
}

