package com.dbms.csmq.model.search;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 21 15:52:36 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SimplePTSearchRVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Rnum {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MeddraLevel {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MeddraExtension {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MeddraCode {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MeddraTerm {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PtCode {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PtName {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MeddraLevelNumber {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TmsRelationScope {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TmsStatus {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MeddraDictContentId {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PtContentId {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ApprovedFlag {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Status {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Value2 {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Value4 {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Category {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Value3 {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreatedBy {
            protected Object get(SimplePTSearchRVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(SimplePTSearchRVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(SimplePTSearchRVORowImpl object);

        protected abstract void put(SimplePTSearchRVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int RNUM = AttributesEnum.Rnum.index();
    public static final int MEDDRALEVEL = AttributesEnum.MeddraLevel.index();
    public static final int MEDDRAEXTENSION = AttributesEnum.MeddraExtension.index();
    public static final int MEDDRACODE = AttributesEnum.MeddraCode.index();
    public static final int MEDDRATERM = AttributesEnum.MeddraTerm.index();
    public static final int PTCODE = AttributesEnum.PtCode.index();
    public static final int PTNAME = AttributesEnum.PtName.index();
    public static final int MEDDRALEVELNUMBER = AttributesEnum.MeddraLevelNumber.index();
    public static final int TMSRELATIONSCOPE = AttributesEnum.TmsRelationScope.index();
    public static final int TMSSTATUS = AttributesEnum.TmsStatus.index();
    public static final int MEDDRADICTCONTENTID = AttributesEnum.MeddraDictContentId.index();
    public static final int PTCONTENTID = AttributesEnum.PtContentId.index();
    public static final int APPROVEDFLAG = AttributesEnum.ApprovedFlag.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int VALUE2 = AttributesEnum.Value2.index();
    public static final int VALUE4 = AttributesEnum.Value4.index();
    public static final int CATEGORY = AttributesEnum.Category.index();
    public static final int VALUE3 = AttributesEnum.Value3.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SimplePTSearchRVORowImpl() {
    }
}

