package com.dbms.csmq.model.impact.client;

import com.dbms.csmq.model.impact.common.ImpactModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 03 12:01:43 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImpactModuleClient extends ApplicationModuleImpl implements ImpactModule {
    /**
     * This is the default constructor (do not remove).
     */
    public ImpactModuleClient() {
    }


    public void loadPrevVersionCurrentNFurteMQDetails(Long dictContentId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"loadPrevVersionCurrentNFurteMQDetails",new String [] {"java.lang.Long"},new Object[] {dictContentId});
        return;
    }


    public void ImpactAssesmentClearSelectMQ() {
        Object _ret = this.riInvokeExportedMethod(this, "ImpactAssesmentClearSelectMQ", null, null);
        return;
    }

    public void executeImpactSearchListVO_CMQ_N() {
        Object _ret = this.riInvokeExportedMethod(this, "executeImpactSearchListVO_CMQ_N", null, null);
        return;
    }

    public void executeImpactSearchListVO_CMQ_Y() {
        Object _ret = this.riInvokeExportedMethod(this, "executeImpactSearchListVO_CMQ_Y", null, null);
        return;
    }

    public void executeImpactSearchListVO_MQ_N() {
        Object _ret = this.riInvokeExportedMethod(this, "executeImpactSearchListVO_MQ_N", null, null);
        return;
    }

    public void executeImpactSearchListVO_MQ_Y() {
        Object _ret = this.riInvokeExportedMethod(this, "executeImpactSearchListVO_MQ_Y", null, null);
        return;
    }

    public void executeImpactSearchListVO_NMQ_N() {
        Object _ret = this.riInvokeExportedMethod(this, "executeImpactSearchListVO_NMQ_N", null, null);
        return;
    }

    public void executeImpactSearchListVO_NMQ_Y() {
        Object _ret = this.riInvokeExportedMethod(this, "executeImpactSearchListVO_NMQ_Y", null, null);
        return;
    }

    public void executePreviousImpactSearchListVO_CMQ_N() {
        Object _ret = this.riInvokeExportedMethod(this, "executePreviousImpactSearchListVO_CMQ_N", null, null);
        return;
    }

    public void executePreviousImpactSearchListVO_CMQ_Y() {
        Object _ret = this.riInvokeExportedMethod(this, "executePreviousImpactSearchListVO_CMQ_Y", null, null);
        return;
    }

    public void executePreviousImpactSearchListVO_MQ_N() {
        Object _ret = this.riInvokeExportedMethod(this, "executePreviousImpactSearchListVO_MQ_N", null, null);
        return;
    }

    public void executePreviousImpactSearchListVO_MQ_Y() {
        Object _ret = this.riInvokeExportedMethod(this, "executePreviousImpactSearchListVO_MQ_Y", null, null);
        return;
    }

    public void executePreviousImpactSearchListVO_NMQ_N() {
        Object _ret = this.riInvokeExportedMethod(this, "executePreviousImpactSearchListVO_NMQ_N", null, null);
        return;
    }

    public void executePreviousImpactSearchListVO_NMQ_Y() {
        Object _ret = this.riInvokeExportedMethod(this, "executePreviousImpactSearchListVO_NMQ_Y", null, null);
        return;
    }

    public void loadPrevVersionCurrentMQDetails(Long dictContentId, Boolean showImpactedOnly) {
        Object _ret =
            this.riInvokeExportedMethod(this, "loadPrevVersionCurrentMQDetails",
                                        new String[] { "java.lang.Long", "java.lang.Boolean" },
                                        new Object[] { dictContentId, showImpactedOnly });
        return;
    }

    public void loadPrevVersionCurrentNFurteMQDetails(Long dictContentId, Boolean showImpactedOnly) {
        Object _ret =
            this.riInvokeExportedMethod(this, "loadPrevVersionCurrentNFurteMQDetails",
                                        new String[] { "java.lang.Long", "java.lang.Boolean" },
                                        new Object[] { dictContentId, showImpactedOnly });
        return;
    }

    public void loadPrevVersionFurteMQDetails(Long dictContentId, Boolean showImpactedOnly) {
        Object _ret =
            this.riInvokeExportedMethod(this, "loadPrevVersionFurteMQDetails",
                                        new String[] { "java.lang.Long", "java.lang.Boolean" },
                                        new Object[] { dictContentId, showImpactedOnly });
        return;
    }

    public void onCurrentVerImpactSearch(String searchLevelStr, String searchTermStr, String searchCodeStr,
                                         String status, String state, String searchProduct) {
        Object _ret =
            this.riInvokeExportedMethod(this, "onCurrentVerImpactSearch",
                                        new String[] { "java.lang.String", "java.lang.String", "java.lang.String",
                                                       "java.lang.String", "java.lang.String", "java.lang.String" },
                                        new Object[] { searchLevelStr, searchTermStr, searchCodeStr, status, state,
                                                       searchProduct });
        return;
    }

    public void onPreviousVerImpactSearch(String searchLevelStr, String searchTermStr, String searchCodeStr) {
        Object _ret =
            this.riInvokeExportedMethod(this, "onPreviousVerImpactSearch",
                                        new String[] { "java.lang.String", "java.lang.String", "java.lang.String" },
                                        new Object[] { searchLevelStr, searchTermStr, searchCodeStr });
        return;
    }

    public void onPreviousVerImpactSearch(String searchLevelStr, String searchTermStr, String searchCodeStr,
                                          String status, String state, String searchProduct) {
        Object _ret =
            this.riInvokeExportedMethod(this, "onPreviousVerImpactSearch",
                                        new String[] { "java.lang.String", "java.lang.String", "java.lang.String",
                                                       "java.lang.String", "java.lang.String", "java.lang.String" },
                                        new Object[] { searchLevelStr, searchTermStr, searchCodeStr, status, state,
                                                       searchProduct });
        return;
    }

    public void previousImpactVersionClearSelectMQ() {
        Object _ret = this.riInvokeExportedMethod(this, "previousImpactVersionClearSelectMQ", null, null);
        return;
    }
}
