package com.dbms.csmq.model.impact.client;

import com.dbms.csmq.model.impact.common.ImpactModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 03 12:01:43 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImpactModuleClient extends ApplicationModuleImpl implements ImpactModule {
    /**
     * This is the default constructor (do not remove).
     */
    public ImpactModuleClient() {
    }


    public void loadPrevVersionCurrentNFurteMQDetails(Long dictContentId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"loadPrevVersionCurrentNFurteMQDetails",new String [] {"java.lang.Long"},new Object[] {dictContentId});
        return;
    }

    public void loadPrevVersionCurrentMQDetails(Long dictContentId, Boolean showImpactedOnly) {
        Object _ret =
            this.riInvokeExportedMethod(this,"loadPrevVersionCurrentMQDetails",new String [] {"java.lang.Long","java.lang.Boolean"},new Object[] {dictContentId, showImpactedOnly});
        return;
    }

    public void loadPrevVersionCurrentNFurteMQDetails(Long dictContentId, Boolean showImpactedOnly) {
        Object _ret =
            this.riInvokeExportedMethod(this,"loadPrevVersionCurrentNFurteMQDetails",new String [] {"java.lang.Long","java.lang.Boolean"},new Object[] {dictContentId, showImpactedOnly});
        return;
    }

    public void loadPrevVersionFurteMQDetails(Long dictContentId, Boolean showImpactedOnly) {
        Object _ret =
            this.riInvokeExportedMethod(this,"loadPrevVersionFurteMQDetails",new String [] {"java.lang.Long","java.lang.Boolean"},new Object[] {dictContentId, showImpactedOnly});
        return;
    }

    public void onPreviousVerImpactSearch(String searchLevelStr, String searchTermStr, String searchCodeStr) {
        Object _ret =
            this.riInvokeExportedMethod(this,"onPreviousVerImpactSearch",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {searchLevelStr, searchTermStr, searchCodeStr});
        return;
    }
}
